name: Publish

on:
  push:
    branches:
    - sources

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Compile LaTeX sources
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          slides/organization.tex
          slides/slides.tex
    - name: Create output directory
      run: mkdir dist
    - run: ls -R
    - name: Move PDFs
      run: mv **/*.pdf ./dist
    - name: Move readme
      run: mv ./README.md ./dist
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: master
        publish_dir: ./dist
        allow_empty_commit: true
        force_orphan: true
